//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleContentoresV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimentacao
    {
        public int id { get; set; }
        public string rt_load { get; set; }
        public System.DateTime dt_load { get; set; }
        public int idProduto { get; set; }
        public int idVolume { get; set; }
        public string id_embalagem { get; set; }
        public int idSituacao { get; set; }
        public Nullable<System.DateTime> dt_uso { get; set; }
        public string rt_backload { get; set; }
        public Nullable<System.DateTime> dt_backload { get; set; }
        public string comentario { get; set; }
    
        public virtual produtoQuimico produtoQuimico { get; set; }
        public virtual situacao situacao { get; set; }
        public virtual volume volume { get; set; }
    }
}
