//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleContentoresV2.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class usuario
    {

        private ControleContentoresEntities db = new ControleContentoresEntities();
        public string nomeUsuario { get; set; }
        public string senhaUsuario { get; set; }
        public int idPerfilUsuario { get; set; }
        public int idUsuario { get; set; }
        public string chaveUsuario { get; set; }
    
        public virtual perfilUsuario perfilUsuario { get; set; }

        public bool Login()
        {
            var result = false;
            var results = db.usuario.Where(u => u.chaveUsuario == this.chaveUsuario);
            var dados = results.ToList();

            try
            {

                foreach (var item in dados)
                {
                    if (this.senhaUsuario == item.senhaUsuario.ToString())
                    {
                        this.chaveUsuario = item.chaveUsuario.ToString();
                        result = true;
                    }
                }
                return result;

            }
            catch
            {
                return result;
            }

        }

        public string IdentificarNome()
        {
            var nome = "";

            if (Login())
            {
                nome = this.chaveUsuario;
            }

            return nome;
        }

        public string IdentificarPerfil()
        {
            var resultsPerfis = db.perfilUsuario;
            var dadosPerfis = resultsPerfis.ToList();
            var perfilUsuario = "";
            //var result = false;
            var results = db.usuario.Where(u => u.chaveUsuario == this.chaveUsuario);
            var dadosUsuario = results.ToList();

            foreach (var dado in dadosPerfis)
            {
                foreach (var perfil in dadosUsuario)
                {
                    if (dado.idPerfilUsuario.ToString() == perfil.idPerfilUsuario.ToString())
                    {
                        perfilUsuario = dado.tipoPerfil.ToString();
                    }
                }
            }

            if (Login())
            {
                return perfilUsuario;
            }

            return null;
        }
    }
}
